\version "2.24.0"

tempoB-XLIXKyrie = \tempoMarkup "Allegro"
  tempoB-XLIXChriste = \tempoMarkup "Largo"
tempoB-XLIXGloria = \tempoMarkup "Andante"
  tempoB-XLIXQuiTollis = \tempoMarkup "Adagio"
tempoB-XLIXCredo = \tempoMarkup "[no tempo]"
  tempoB-XLIXQuiPropter = \tempoMarkup "Adagio"
  tempoB-XLIXEtResurrexit = \tempoMarkup "Allegro"
tempoB-XLIXSanctus = \tempoMarkup "Presto"
  tempoB-XLIXPleni = \tempoMarkup "[no tempo]"
tempoB-XLIXBenedictus = \tempoMarkup "[no tempo]"
  tempoB-XLIXOsanna = \tempoMarkup "[no tempo]"
tempoB-XLIXAgnus = \tempoMarkup "Andante"
  tempoB-XLIXDona = \tempoMarkup "Andante"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
