\version "2.24.0"

tempoJ-IVa = \tempoMarkup "Vivace"
tempoJ-IVb = \tempoMarkup "Andante"
tempoJ-IVc = \tempoMarkup "Allegro"
tempoJ-IVd = \tempoMarkup "Andante"
tempoJ-IVe = \tempoMarkup "[Tempo deest]"

\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/timp.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/chords.ly"
\include "notes/org.ly"
