\version "2.24.0"

tempoE-XXVIIIa = \tempoMarkup "Chorus · Andante"
tempoE-XXVIIIba = \tempoMarkup "Allegretto non troppo / Vivace in tempo schietto"
  tempoE-XXVIIIbb = \tempoMarkup "Tempo giusto"
tempoE-XXVIIIc = \tempoMarkup "Largo"
tempoE-XXVIIId = \tempoMarkup "Vivace"

\include "notes/ob1.ly"
\include "notes/ob2.ly"
\include "notes/chalumeau1.ly"
\include "notes/chalumeau2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/chords.ly"
\include "notes/org.ly"
