\version "2.24.0"

tempoXCVIIa = \tempoMarkup "Andante"
tempoXCVIIb = \tempoMarkup "Passato"
tempoXCVIIc = \tempoMarkup "Presto"
tempoXCVIId = \tempoMarkup "Adagio"
tempoXCVIIe = \tempoMarkup "[Alla breve]"
tempoXCVIIf = \tempoMarkup "Largo"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
