\version "2.24.0"

tempoD-I-V = \tempoMarkup "Allegro"
tempoD-I-V-b = \tempoMarkup "[Tempo deest]"
tempoD-I-V-c = \tempoMarkup "Recitativo · Adagio"
tempoD-I-V-d = \tempoMarkup "Aria · Allegro non molto"
tempoD-I-V-e = \tempoMarkup "Allegro"

\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/timp.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
