\version "2.24.0"

markAriaDaCapo = {
  \once \override Score.RehearsalMark.self-alignment-X = #RIGHT
  \mark \markup \remark "Aria da capo"
}

Barak = \markup { \override #'(box-padding . 0.5) \box "Barak" }
Debora = \markup { \override #'(box-padding . 0.5) \box "Debora" }
Jahel = \markup { \override #'(box-padding . 0.5) \box "Jahel" }
Sisera = \markup { \override #'(box-padding . 0.5) \box "Sisera" }
frma = \markup \remark "ferma"

tempoA-XIXIntroa = \tempoMarkup "Vivace"
  tempoA-XIXIntroB = \tempoMarkup "Molto allegro"
tempoA-XIXAScenaPrima = \tempoMarkup "Adagiose"
tempoA-XIXAScenaSecunda = \tempoMarkup "Recitativo"
tempoA-XIXAAriaPrima = \tempoMarkup "Spirituoso"
  tempoA-XIXAAriaPrimaB = \tempoMarkup "Andante"
tempoA-XIXAScenaTertia = \tempoMarkup "Recitativo"
tempoA-XIXAScenaQuarta = \tempoMarkup "[Recitativo]"
tempoA-XIXAAriaSecunda = \tempoMarkup "Allegro"
  tempoA-XIXAAriaSecundaB = \tempoMarkup "Andante"
tempoA-XIXAScenaQuinta = \tempoMarkup "Recitativo, Adagio"
tempoA-XIXAAriaTertia = \tempoMarkup "Vivace"
  tempoA-XIXAAriaTertiaB = \tempoMarkup "Allegretto"
tempoA-XIXAScenaSexta = \tempoMarkup "Recitativo"
tempoA-XIXAAriaQuarta = \tempoMarkup "Largo"
  tempoA-XIXAAriaQuartaB = \tempoMarkup "Andante"
  tempoA-XIXAAriaQuartaC = \tempoMarkup "Adagio"
tempoA-XIXAScenaSeptima = \tempoMarkup "Recitativo"
tempoA-XIXAChorusA = \tempoMarkup "[Chor Israels,] Largo"
  tempoA-XIXAChorusAb = \tempoMarkup "Recitativo"
  tempoA-XIXAChorusAc = \tempoMarkup "Chor der Cananiter"
  tempoA-XIXAChorusAd = \tempoMarkup "[Chor Israels]"
  tempoA-XIXAChorusAe = \tempoMarkup "Recitativo"
  tempoA-XIXAChorusAf = \tempoMarkup "Chor der Cananiter"
  tempoA-XIXAChorusAg = \tempoMarkup "Recitativo"
  tempoA-XIXAChorusAh = \tempoMarkup "Chor der Cananiter"
  tempoA-XIXAChorusAi = \tempoMarkup "Chor Israels"
  tempoA-XIXAChorusAj = \tempoMarkup "Recitativo"
  tempoA-XIXAChorusAk = \tempoMarkup "Cananiter Chor"
  tempoA-XIXAChorusAl = \tempoMarkup "Recitativo"
tempoA-XIXAChorusB = \tempoMarkup "Tempo ordinario"

tempoA-XIXBScenaPrima = \tempoMarkup "Recitativo"
  tempoA-XIXBScenaPrimaB = \tempoMarkup "Ariose"
tempoA-XIXBAriaPrima = \tempoMarkup "Allegro"
  tempoA-XIXBAriaPrimaB = \tempoMarkup "Andante"
tempoA-XIXBScenaSecunda = \tempoMarkup "Recitativo"
  tempoA-XIXBScenaSecundaB = \tempoMarkup "Ariose"
tempoA-XIXBAriaSecunda = \tempoMarkup "Vivace"
  tempoA-XIXBAriaSecundaB = \tempoMarkup "Larghetto"
tempoA-XIXBScenaTertia = \tempoMarkup "Recitativo"
  tempoA-XIXBScenaTertiaB = \tempoMarkup "Ariose"
  tempoA-XIXBScenaTertiaC = \tempoMarkup "Ariose"
  tempoA-XIXBScenaTertiaD = \tempoMarkup "Ariose"
  tempoA-XIXBScenaTertiaE = \tempoMarkup "Largo"
  tempoA-XIXBScenaTertiaF = \tempoMarkup "Recitativo"
  tempoA-XIXBScenaTertiaG = \tempoMarkup "Ariose Adagio"
tempoA-XIXBAriaTertia = \tempoMarkup "Molto largo"
  tempoA-XIXBAriaTertiaB = \tempoMarkup "Allegretto"
  tempoA-XIXBAriaTertiaC = \tempoMarkup "Adagio"
tempoA-XIXBScenaQuarta = \tempoMarkup "Recitativo"
  tempoA-XIXBScenaQuartaB = \tempoMarkup "Adagio"
  tempoA-XIXBScenaQuartaC = \tempoMarkup "Ariose"
  tempoA-XIXBScenaQuartaD = \tempoMarkup "Ariose"
tempoA-XIXBAriaQuarta = \tempoMarkup "Allegretto mà non troppo"
  tempoA-XIXBAriaQuartaB = \tempoMarkup "Vivace"
tempoA-XIXBScenaQuinta = \tempoMarkup "Recitativo"
tempoA-XIXBChorus = \tempoMarkup "Tempo ordinario"
  tempoA-XIXBChorusB = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/vla.ly"
\include "notes/soli.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/bc.ly"
