\version "2.24.0"

markKyrieUtSupra = {
  \once \override Score.RehearsalMark.self-alignment-X = #RIGHT
  \mark \markup \remark "Kyrie ut supra"
}

tempoB-LXXVIKyrie = \tempoMarkup "Vivace"
  tempoB-LXXVIChriste = \tempoTitleMarkup "Christe" "Andante"
tempoB-LXXVIGloria = \tempoTitleMarkup "Et in terra" "Vivace"
  tempoB-LXXVIGratias = \tempoTitle "Gratias"
  tempoB-LXXVIDomine = \tempoTitle "Domine Deus"
  tempoB-LXXVIQuiTollis = \tempoTitleMarkup "Qui tollis" "Largo"
  tempoB-LXXVIQuiTollisB = \tempoTitle "Qui tollis"
  tempoB-LXXVISuscipe = \tempoTitle "Suscipe"
  tempoB-LXXVIMiserere = \tempoTitle "Miserere"
  tempoB-LXXVIQuoniam = \tempoTitleMarkup "Quoniam" "Andante"
  tempoB-LXXVICumSancto = \tempoTitleMarkup "Cum Sancto" "Allegro"
tempoB-LXXVICredo = \tempoTitleMarkup "Patrem" "Andante"
  tempoB-LXXVIEtInUnum = \tempoTitle "Et in unum"
  tempoB-LXXVIDeumDeDeo = \tempoTitle "Deum de Deo"
  tempoB-LXXVIQuiPropter = \tempoTitle "Qui propter"
  tempoB-LXXVIEtIncarnatus = \tempoTitleMarkup "Et incarnatus" "Largo"
  tempoB-LXXVICrucifixus = \tempoTitleMarkup "Crucifixus" "Tempo giusto"
  tempoB-LXXVIEtResurrexit = \tempoTitleMarkup "Et resurrexit" "Allegro"
  tempoB-LXXVIEtAscendit = \tempoTitle "Et ascendit"
  tempoB-LXXVIEtInSpiritum = \tempoTitle "Et in Spiritum"
  tempoB-LXXVISimul = \tempoTitle "Simul"
  tempoB-LXXVIEtVitam = \tempoTitleMarkup "Et vitam" "Vivace"
tempoB-LXXVISanctus = \tempoMarkup "Molto andante"
  tempoB-LXXVIPleni = \tempoTitle "Pleni sunt"
  tempoB-LXXVIOsanna = \tempoTitle "Osanna"
tempoB-LXXVIBenedictus = \tempoMarkup "Larghetto"
  tempoB-LXXVIOsannaB = \tempoTitleMarkup "Osanna" "Presto"
tempoB-LXXVIAgnus = \tempoMarkup "Adagio"
  tempoB-LXXVIDona = \tempoTitleMarkup "Dona" "Allegretto"

\include "notes/org.ly"
