\version "2.24.0"

tempoH-I-XIIIDixit = \tempoMarkup "[no tempo]"
tempoH-I-XIIIConfitebor = \tempoMarkup "Vivace"
tempoH-I-XIIIBeatus = \tempoMarkup "[no tempo]"
tempoH-I-XIIIPueri = \tempoMarkup "[no tempo]"
tempoH-I-XIIILaudate = \tempoMarkup "[no tempo]"
tempoH-I-XIIIMagnificat = \tempoMarkup "[no tempo]"

\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/timp.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
