\version "2.24.0"

tempoH-I-IX-a = \tempoMarkup "Andante"
tempoH-I-IX-b = \tempoMarkup "Andante"
tempoH-I-IX-c = \tempoMarkup "Presto"
tempoH-I-IX-d = \tempoMarkup "Allegro / Vivace"
tempoH-I-IX-f = \tempoMarkup "Andante"
  tempoH-I-IX-fb = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
