\version "2.24.0"

markOsannaUtSupra = {
  \once \override Score.RehearsalMark.self-alignment-X = #RIGHT
  \mark \markup \remark "Osanna ut supra"
}

tempoB-LXXVKyrie = \tempoMarkup "Vivace"
  tempoB-LXXVChriste = \tempoTitleMarkup "Christe" "Andante"
  tempoB-LXXVKyrieFuga = \tempoMarkup "Allegro"
tempoB-LXXVGloria = \tempoMarkup "Allegro"
  tempoB-LXXVLaudamus = \tempoTitleMarkup "Laudamus" "Larghetto"
  tempoB-LXXVGratias = \tempoTitleMarkup "Gratias" "Largo"
  tempoB-LXXVPropter = \tempoMarkup "Vivace"
  tempoB-LXXVDomine = \tempoTitleMarkup "Domine" "Andante"
  tempoB-LXXVQuiTollis = \tempoTitleMarkup "Qui tollis" "Adagio"
  tempoB-LXXVQuiSedes = \tempoTitleMarkup "Qui sedes" "Allegro"
  tempoB-LXXVQuoniam = \tempoTitleMarkup "Quoniam" "Ariose"
  tempoB-LXXVCumSancto = \tempoTitleMarkup "Cum Sancto" "Tempo ordinario"
  tempoB-LXXVCumSanctoFuga = \tempoMarkup "Allegro"
tempoB-LXXVCredo = \tempoMarkup "Vivace"
  tempoB-LXXVEtIncarnatus = \tempoTitleMarkup "Et incarnatus" "Largo"
  tempoB-LXXVCrucifixus = \tempoTitleMarkup "Crucifixus" "Adagiose"
  tempoB-LXXVEtResurrexit = \tempoTitleMarkup "Et resurrexit" "Vivace"
  tempoB-LXXVEtInSpiritum = \tempoTitleMarkup "Et in Spiritum" "Andante"
  tempoB-LXXVEtVitam = \tempoTitleMarkup "Et vitam" "Allegro"
tempoB-LXXVSanctus = \tempoMarkup "Allegro"
  tempoB-LXXVPleni = \tempoTitleMarkup "Pleni" "Tempo giusto"
  tempoB-LXXVOsanna = \tempoMarkup "[Tempo deest]"
tempoB-LXXVBenedictus = \tempoMarkup "Larghetto"
tempoB-LXXVAgnus = \tempoMarkup "Vivace"
  tempoB-LXXVDona = \tempoTitleMarkup "Dona" "Allegro"

\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
