\version "2.24.0"

Job = \markup \remark "Job"
JobsFrau = \markup \remark "Jobs Frau"
Eliphas = \markup \remark "Eliphas"
fC = \set Staff.forceClef = ##t

tempoA-XIIIntro = \tempoMarkup "Adagiosè"
  tempoA-XIIIntroB = \tempoMarkup "Vivace passato"
tempoA-XIIScenaPrima = \tempoMarkup "Recitativo"
  tempoA-XIIScenaPrimaB = \tempoMarkup "Ariosè"
tempoA-XIIAriaPrima = \tempoMarkup "Andante"
tempoA-XIIScenaSecunda = \tempoMarkup "Recitativo"
tempoA-XIIAriaSecunda = \tempoMarkup "Presto moderato"
  tempoA-XIIAriaSecundaB = \tempoMarkup "Largo"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/vla.ly"
\include "notes/soli.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/bc.ly"
