\version "2.24.0"

tempoB-XXXVIIIKyrie = \tempoMarkup "Allegro"
  tempoB-XXXVIIIChriste = \tempoMarkup "Larghetto"
  tempoB-XXXVIIIKyrieB = \tempoMarkup "Allegro"
tempoB-XXXVIIIGloria = \tempoMarkup "Allegro"
  tempoB-XXXVIIIQuiTollis = \tempoMarkup "Adagio"
  tempoB-XXXVIIIQuiSedes = \tempoMarkup "Allegro"
  tempoB-XXXVIIIQuoniam = \tempoMarkup "Andante"
  tempoB-XXXVIIICumSancto = \tempoMarkup "Largo"
  tempoB-XXXVIIIAmen = \tempoMarkup "Vivace"
tempoB-XXXVIIICredo = \tempoMarkup "Vivace"
  tempoB-XXXVIIIEtIncarnatus = \tempoMarkup "Largo"
  tempoB-XXXVIIIEtResurrexit = \tempoMarkup "Allegretto"
  tempoB-XXXVIIIEtUnam = \tempoMarkup "Larghetto"
  tempoB-XXXVIIIEtVitam = \tempoMarkup "Allegro"
tempoB-XXXVIIISanctus = \tempoMarkup "Larghetto"
  tempoB-XXXVIIIPleni = \tempoMarkup "Vivace"
tempoB-XXXVIIIBenedictus = \tempoMarkup "Larghetto"
  tempoB-XXXVIIIOsanna = \tempoMarkup "Presto"
tempoB-XXXVIIIAgnus = \tempoMarkup "Largo"
  tempoB-XXXVIIIDona = \tempoMarkup "Presto"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
