\version "2.24.0"

tempoD-I-XIVa = \tempoMarkup "Vivace"
tempoD-I-XIVb = \tempoMarkup "Largo"
tempoD-I-XIVc = \tempoMarkup "Vivace"
tempoD-I-XIVd = \tempoMarkup "Recitativo"
tempoD-I-XIVe = \tempoMarkup "Aria · Molto allegro"
tempoD-I-XIVf = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
