\version "2.24.0"

tempoB-LXXKyrie = \tempoMarkup "Vivace"
  tempoB-LXXChriste = \tempoMarkup "Ordinario"
tempoB-LXXGloria = \tempoMarkup "Vivace"
tempoB-LXXCredo = \tempoMarkup "Vivace"
  tempoB-LXXEtIncarnatus = \tempoMarkup "Largo"
  tempoB-LXXEtResurrexit = \tempoMarkup "Vivace"
  tempoB-LXXEtVitam = \tempoMarkup "Allegro"
tempoB-LXXSanctus = \tempoMarkup "Adagio"
  tempoB-LXXPleni = \tempoMarkup "Allegro"
  tempoB-LXXOsanna = \tempoTitleMarkup "Osanna" "Presto"
tempoB-LXXBenedictus = \tempoMarkup "Andante"
tempoB-LXXAgnus = \tempoMarkup "Adagio"
  tempoB-LXXDona = \tempoMarkup "Presto"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
