\version "2.24.0"

tempoB-LXXIVKyrie = \tempoMarkup "Allegro"
  tempoB-LXXIVChriste = \tempoTitle "Christe"
tempoB-LXXIVGloria = \tempoTitleMarkup "Et in terra" "Vivace"
  tempoB-LXXIVLaudamus = \tempoTitle "Laudamus"
  tempoB-LXXIVGratias = \tempoTitle "Gratias"
  tempoB-LXXIVDomine = \tempoTitle "Domine Deus"
  tempoB-LXXIVQuiTollis = \tempoTitleMarkup "Qui tollis" "Largo"
  tempoB-LXXIVQuiSedes = \tempoTitleMarkup "Qui sedes" "Vivace"
  tempoB-LXXIVQuoniam = \tempoTitle "[Quoniam]"
  tempoB-LXXIVCumSancto = \tempoTitleMarkup "Cum Sancto" "Largo"
  tempoB-LXXIVAmen = \tempoTitleMarkup "Amen" "Alla capella · Moderato"
tempoB-LXXIVCredo = \tempoTitleMarkup "Patrem" "Allegro"
  tempoB-LXXIVEtInUnum = \tempoTitle "Et in unum"
  tempoB-LXXIVEtExPatre = \tempoTitle "Et ex Patre"
  tempoB-LXXIVGenitum = \tempoTitle "Genitum"
  tempoB-LXXIVQuiPropter = \tempoTitle "Qui propter"
  tempoB-LXXIVEtIncarnatus = \tempoTitleMarkup "Et incarnatus" "Adagio"
  tempoB-LXXIVCrucifixus = \tempoTitle "Crucifixus"
  tempoB-LXXIVEtResurrexit = \tempoTitleMarkup "Et resurrexit" "Allegro"
  tempoB-LXXIVEtIterum = \tempoTitle "Et iterum"
  tempoB-LXXIVIudicare = \tempoTitle "Iudicare"
  tempoB-LXXIVCuius = \tempoTitle "Cuius"
  tempoB-LXXIVEtInSpiritum = \tempoTitle "Et in Spiritum"
  tempoB-LXXIVSimul = \tempoTitle "Simul"
  tempoB-LXXIVEtUnam = \tempoTitle "Et unam"
  tempoB-LXXIVConfiteor = \tempoTitle "Confiteor"
  tempoB-LXXIVEtExpecto = \tempoTitle "Et expecto"
  tempoB-LXXIVMortuorum = \tempoTitle "Mortuorum"
  tempoB-LXXIVEtVitam = \tempoTitleMarkup "Et vitam" "Allegro"
tempoB-LXXIVSanctus = \tempoMarkup "Larghetto"
  tempoB-LXXIVPleni = \tempoTitleMarkup "Pleni sunt" "Vivace"
  tempoB-LXXIVOsanna = \tempoTitleMarkup "Osanna" "Presto"
tempoB-LXXIVBenedictus = \tempoMarkup "Spirituoso"
tempoB-LXXIVAgnus = \tempoMarkup "Largo"
  tempoB-LXXIVDona = \tempoTitleMarkup "Dona" "Presto"

\include "notes/org.ly"
