\version "2.24.0"

markOsannaUtSupra = {
  \once \override Score.RehearsalMark.self-alignment-X = #RIGHT
  \mark \markup \remark "Osanna ut supra"
}
bfdot = \markup { \combine \transparent \figured-bass 0 \raise #.6 \draw-circle #.2 #0 ##t }

tempoB-LXXIVKyrie = \tempoMarkup "Allegro"
  tempoB-LXXIVChriste = \tempoMarkup "Christe"
tempoB-LXXIVGloria = \tempoMarkup "Et in terra · Vivace"
  tempoB-LXXIVLaudamus = \tempoMarkup "Laudamus"
  tempoB-LXXIVGratias = \tempoMarkup "Gratias"
  tempoB-LXXIVDomine = \tempoMarkup "Domine Deus"
  tempoB-LXXIVQuiTollis = \tempoMarkup "Qui tollis · Largo"
  tempoB-LXXIVQuiSedes = \tempoMarkup "Qui sedes · Vivace"
  tempoB-LXXIVQuoniam = \tempoMarkup "[Quoniam]"
  tempoB-LXXIVCumSancto = \tempoMarkup "Cum Sancto · Largo"
  tempoB-LXXIVAmen = \tempoMarkup "Amen · Alla capella · Moderato"
tempoB-LXXIVCredo = \tempoMarkup "Patrem · Allegro"
  tempoB-LXXIVEtInUnum = \tempoMarkup "Et in unum"
  tempoB-LXXIVEtExPatre = \tempoMarkup "Et ex Patre"
  tempoB-LXXIVGenitum = \tempoMarkup "Genitum"
  tempoB-LXXIVQuiPropter = \tempoMarkup "Genitum"
  tempoB-LXXIVEtIncarnatus = \tempoMarkup "Et incarnatus · Adagio"
  tempoB-LXXIVCrucifixus = \tempoMarkup "Crucifixus"
  tempoB-LXXIVEtResurrexit = \tempoMarkup "Et resurrexit · Allegro"
  tempoB-LXXIVEtIterum = \tempoMarkup "Et iterum"
  tempoB-LXXIVIudicare = \tempoMarkup "Iudicare"
  tempoB-LXXIVCuius = \tempoMarkup "Cuius"
  tempoB-LXXIVEtInSpiritum = \tempoMarkup "Et in Spiritum"
  tempoB-LXXIVSimul = \tempoMarkup "Simul"
  tempoB-LXXIVEtUnam = \tempoMarkup "Et unam"
  tempoB-LXXIVConfiteor = \tempoMarkup "Confiteor"
  tempoB-LXXIVEtExpecto = \tempoMarkup "Et expecto"
  tempoB-LXXIVMortuorum = \tempoMarkup "Mortuorum"
  tempoB-LXXIVEtVitam = \tempoMarkup "Et vitam · Allegro"
tempoB-LXXIVSanctus = \tempoMarkup "Larghetto"
  tempoB-LXXIVPleni = \tempoMarkup "Pleni sunt · Vivace"
  tempoB-LXXIVOsanna = \tempoMarkup "Osanna · Presto"
tempoB-LXXIVBenedictus = \tempoMarkup "Spirituoso"
tempoB-LXXIVAgnus = \tempoMarkup "Largo"
  tempoB-LXXIVDona = \tempoMarkup "Dona · Presto"

\include "notes/org.ly"
