\version "2.24.0"

tempoB-LXIIIKyrie = \tempoTitleMarkup "Alla capella" "Allegro"
  tempoB-LXIIIChriste = \tempoTitleMarkup "Christe" "[no tempo]"
tempoB-LXIIICredo = \tempoMarkup "[no tempo]"
  tempoB-LXIIIEtIncarnatus = \tempoTitleMarkup "Et incarnatus est" "Largo"
  tempoB-LXIIICrucifixus = \tempoTitleMarkup "Crucifixus" "[no tempo]"
  tempoB-LXIIIEtResurrexit = \tempoTitleMarkup "Et resurrexit" "[no tempo]"
tempoB-LXIIISanctus = \tempoMarkup "[no tempo]"
  tempoB-LXIIIOsanna = \tempoTitleMarkup "Osanna" "[no tempo]"
tempoB-LXIIIBenedictus = \tempoMarkup "[no tempo]"
tempoB-LXIIIAgnus = \tempoMarkup "[no tempo]"
  tempoB-LXIIIDona = \tempoMarkup "[no tempo]"
tempoB-LXIIIFragment = \tempoMarkup "[no tempo]"

\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
