\version "2.24.0"

tempoD-I-VIIIa = \tempoMarkup "Adagio"
tempoD-I-VIIIb = \tempoMarkup "Aria · Largo"
tempoD-I-VIIIc = \tempoMarkup "Allegro"
tempoD-I-VIIId = \tempoMarkup "Adagio"
tempoD-I-VIIIe = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
