\version "2.24.0"

tempoH-I-IIDixit = \tempoMarkup "[no tempo]"
tempoH-I-IIConfiteborA = \tempoMarkup "[no tempo]"
  tempoH-I-IIConfiteborB = \tempoMarkup "Adagio"
  tempoH-I-IIConfiteborC = \tempoMarkup "Andante"
tempoH-I-IIBeatusA = \tempoMarkup "[no tempo]"
  tempoH-I-IIBeatusB = \tempoMarkup "[no tempo]"
  tempoH-I-IIBeatusC = \tempoMarkup "Adagio"
  tempoH-I-IIBeatusD = \tempoMarkup "Andante"
tempoH-I-IIPueriA = \tempoMarkup "[no tempo]"
  tempoH-I-IIPueriB = \tempoMarkup "Alla breve"
tempoH-I-IILaudate = \tempoMarkup "Alla capella"
tempoH-I-IIMagnificatA = \tempoMarkup "Adagio"
  tempoH-I-IIMagnificatB = \tempoMarkup "Allegro"
  tempoH-I-IIMagnificatC = \tempoMarkup "Adagio"
  tempoH-I-IIMagnificatD = \tempoMarkup "Presto"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
