\version "2.24.0"

tempoG-VIa = \tempoMarkup "Andante"
tempoG-VIb = \tempoMarkup "Ariose"
tempoG-VIc = \tempoMarkup "Presto"
tempoG-VId = \tempoMarkup "Largo"
tempoG-VIe = \tempoMarkup "Vivace"
tempoG-VIf = \tempoMarkup "Largo"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
