\version "2.24.0"

tempoB-VIIIKyrie = \tempoMarkup "Ariosè"
  tempoB-VIIIKyrieB = \tempoMarkup "Vivace"
tempoB-VIIIGloria = \tempoMarkup "Andante"
tempoB-VIIICredo = \tempoMarkup "Andante"
  tempoB-VIIIEtIncarnatus = \tempoMarkup "Largo"
  tempoB-VIIIEtResurrexit = \tempoMarkup "Allegro"
tempoB-VIIISanctus = \tempoMarkup "Largo"
  tempoB-VIIISanctusB = \tempoMarkup "Vivace"
tempoB-VIIIBenedictus = \tempoMarkup "Tempo giusto"
  tempoB-VIIIOsanna = \tempoMarkup "Alla capella"
tempoB-VIIIAgnus = \tempoMarkup "Tempo ordinario"
  tempoB-VIIIDona = \tempoMarkup "Presto"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
