\version "2.24.0"

tempoXLVIVeni = \tempoMarkup "Vivace"
tempoXLVICum = \tempoMarkup "Recitativo"
tempoXLVIBeata = \tempoMarkup "Spirituoso"
tempoXLVIExurge = \tempoMarkup "Tempo ordinario"
tempoXLVIAlleluia = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
