\version "2.24.0"

Barmherzigkeit = \markup { \override #'(box-padding . 0.5) \box "Barmherzigkeit" }
Gerechtigkeit = \markup { \override #'(box-padding . 0.5) \box "Gerechtigkeit" }
Adam = \markup { \override #'(box-padding . 0.5) \box "Adam" }
Schöpffer = \markup { \override #'(box-padding . 0.5) \box "Schöpffer" }

tempoA-XIIIIntro = \tempoMarkup "Adagiosè"
  tempoA-XIIIIntroB = \tempoMarkup "Allegro"
  tempoA-XIIIIntroC = \tempoMarkup "Adagio"
tempoA-XIIIScenaPrima = \tempoMarkup "Recitativo"
tempoA-XIIIAriaPrima = \tempoMarkup "Vivace"
  tempoA-XIIIAriaPrimaB = \tempoMarkup "Adagio"
tempoA-XIIIScenaSecunda = \tempoMarkup "Recitativo"
tempoA-XIIIAriaSecunda = \tempoMarkup "Tempo giusto"
tempoA-XIIIScenaTertia = \tempoMarkup "Recitativo"
tempoA-XIIIAriaTertia = \tempoMarkup "Allegro molto"
tempoA-XIIIScenaQuarta = \tempoMarkup "Recitativo"
tempoA-XIIIAriaQuarta = \tempoMarkup "Largo"
tempoA-XIIIScenaQuinta = \tempoMarkup "Recitativo"
tempoA-XIIIChorus = \tempoMarkup "Largo"
  tempoA-XIIIChorusB = \tempoMarkup "Presto moderato"

tempoA-XIIIScenaSexta = \tempoMarkup "Recitativo"
tempoA-XIIIAriaQuinta = \tempoMarkup "Allegro"
tempoA-XIIIScenaSeptima = \tempoMarkup "Recitativo"
tempoA-XIIIAriaSexta = \tempoMarkup "Largo"
  tempoA-XIIIAriaSextaB = \tempoMarkup "Adagio"
tempoA-XIIIScenaOctava = \tempoMarkup "Recitativo"
tempoA-XIIIAriaSeptima = \tempoMarkup "Largo"
  tempoA-XIIIAriaSeptimaB = \tempoMarkup "Allegretto"
tempoA-XIIIScenaNona = \tempoMarkup "Recitativo"
tempoA-XIIIAriaOctava = \tempoMarkup "Tempo giusto"
tempoA-XIIIScenaDecima = \tempoMarkup "Recitativo"
tempoA-XIIIFinale = \tempoMarkup "Largo"
  tempoA-XIIIFinaleB = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/vla.ly"
\include "notes/soli.ly"
\include "notes/S.ly"
\include "notes/T1.ly"
\include "notes/T2.ly"
\include "notes/B.ly"
\include "notes/bc.ly"
