\version "2.24.0"

tempoB-XXXIIIKyrie = \tempoMarkup "Allegro"
tempoB-XXXIIIGloria = \tempoMarkup "Vivace"
  tempoB-XXXIIIQuiTollis = \tempoMarkup "Adagio"
  tempoB-XXXIIIQuiSedes = \tempoMarkup "Vivace"
  tempoB-XXXIIIQuoniam = \tempoMarkup "Andante"
  tempoB-XXXIIIInGloria = \tempoMarkup "Larghetto"
  tempoB-XXXIIIAmen = \tempoMarkup "Presto"
tempoB-XXXIIICredo = \tempoMarkup "Vivace"
  tempoB-XXXIIIEtIncarnatus = \tempoMarkup "Largo"
  tempoB-XXXIIIEtResurrexit = \tempoMarkup "Vivace"
  tempoB-XXXIIIEtInSpiritum = \tempoMarkup "Andante"
  tempoB-XXXIIIEtVitam = \tempoMarkup "Allegro"
tempoB-XXXIIISanctus = \tempoMarkup "Largo"
  tempoB-XXXIIIPleni = \tempoMarkup "Allegro"
tempoB-XXXIIIBenedictus = \tempoMarkup "Largo"
  tempoB-XXXIIIOsanna = \tempoMarkup "Vivace"
tempoB-XXXIIIAgnus = \tempoMarkup "Largo"
  tempoB-XXXIIIDona = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
