\version "2.24.0"

tempoB-LXVIIKyrie = \tempoMarkup "[no tempo]"
  tempoB-LXVIIChriste = \tempoMarkup "[no tempo]"
tempoB-LXVIIGloria = \tempoMarkup "Presto"
  tempoB-LXVIIQuiTollis = \tempoMarkup "Adagio"
  tempoB-LXVIIQuoniam = \tempoMarkup "Allegro"
tempoB-LXVIICredo = \tempoMarkup "[no tempo]"
  tempoB-LXVIIEtIncarnatus = \tempoMarkup "Adagio"
  tempoB-LXVIIEtResurrexit = \tempoMarkup "[no tempo]"
tempoB-LXVIISanctus = \tempoMarkup "[no tempo]"
  tempoB-LXVIIOsanna = \tempoTitleMarkup "Osanna" "[no tempo]"
tempoB-LXVIIBenedictus = \tempoMarkup "[no tempo]"
tempoB-LXVIIAgnus = \tempoMarkup "[no tempo]"
  tempoB-LXVIIDona = \tempoMarkup "Ariosè"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
