\version "2.24.0"

markKyrieUtSupra = {
  \once \override Score.RehearsalMark.self-alignment-X = #RIGHT
  \mark \markup \remark "Kyrie ut supra"
}

tempoB-LXVKyrie = \tempoMarkup "Presto"
  tempoB-LXVChriste = \tempoMarkup "Andante"
tempoB-LXVGloria = \tempoMarkup "[no tempo]"
  tempoB-LXVQuiTollis = \tempoMarkup "Adagio"
  tempoB-LXVCumSancto = \tempoMarkup "Allegro"
tempoB-LXVCredo = \tempoMarkup "Allegro"
  tempoB-LXVQuiPropter = \tempoMarkup "Adagio"
  tempoB-LXVEtResurrexit = \tempoMarkup "Allegro"
tempoB-LXVSanctus = \tempoMarkup "Adagio"
  tempoB-LXVSanctusB = \tempoMarkup "Presto"
tempoB-LXVBenedictus = \tempoMarkup "[no tempo]"
  tempoB-LXVOsanna = \tempoMarkup "[Presto]"
tempoB-LXVBenedictusB = \tempoMarkup "[no tempo]"
  tempoB-LXVOsannaB = \tempoMarkup "[Alla breve]"
tempoB-LXVAgnus = \tempoMarkup "Adagio"
  tempoB-LXVDona = \tempoMarkup "Presto"
tempoB-LXVAgnusB = \tempoMarkup "[no tempo]"
  tempoB-LXVDonaB = \tempoMarkup "[Alla breve]"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
