\version "2.24.0"

tempoD-I-VIIa = \tempoMarkup "Allegro"
tempoD-I-VIIb = \tempoMarkup "Aria · Larghetto"
tempoD-I-VIIc = \tempoMarkup "Allegretto"
tempoD-I-VIId = \tempoMarkup "Largo"
tempoD-I-VIIe = \tempoMarkup "Vivace"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
