\version "2.24.0"

tempoH-I-IIIDixit = \tempoMarkup "Tempo giusto"
  tempoH-I-IIIDixitB = \tempoMarkup "Vivace"
tempoH-I-IIIConfitebor = \tempoMarkup "Moderato"
  tempoH-I-IIIConfiteborB = \tempoMarkup "Vivace"
tempoH-I-IIIBeatus = \tempoMarkup "Andante moderato"
  tempoH-I-IIIBeatusB = \tempoMarkup "Poco andante"
  tempoH-I-IIIBeatusC = \tempoMarkup "Allegro"
tempoH-I-IIIPueri = \tempoMarkup "Allegro mà moderato"
tempoH-I-IIILaudate = \tempoMarkup "Vivace"
  tempoH-I-IIILaudateB = \tempoMarkup "Allegro"
tempoH-I-IIIMagnificat = \tempoMarkup "Andante"
  tempoH-I-IIIMagnificatB = \tempoMarkup "Allegro"
tempoH-I-IIIExitu = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
