\version "2.24.0"

tempoH-II-Ia = \tempoMarkup "Largo"
tempoH-II-Ib = \tempoMarkup "Andante"
tempoH-II-Ic = \tempoMarkup "Allegro"
tempoH-II-Id = \tempoMarkup "Adagio"
tempoH-II-Ie = \tempoMarkup "Presto"
tempoH-II-If = \tempoMarkup "[Tempo deest]"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
