\version "2.24.0"

tempoB-XLIIKyrie = \tempoMarkup "Vivace"
  tempoB-XLIIChriste = \tempoMarkup "Andante"
tempoB-XLIIGloria = \tempoMarkup "Andante"
tempoB-XLIICredo = \tempoMarkup "Andante"
  tempoB-XLIIEtIncarnatus = \tempoMarkup "Largo"
  tempoB-XLIIEtResurrexit = \tempoMarkup "Vivace"
  tempoB-XLIIEtVitam = \tempoMarkup "Allegro"
tempoB-XLIISanctus = \tempoMarkup "Vivace"
  tempoB-XLIIOsanna = \tempoTitleMarkup "Osanna" "Presto"
tempoB-XLIIBenedictus = \tempoMarkup "Andante"
tempoB-XLIIAgnus = \tempoMarkup "Adagio"
  tempoB-XLIIDona = \tempoMarkup "Ariose"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
