\version "2.24.0"

tempoH-I-VIIDixit = \tempoMarkup "[no tempo]"
  tempoH-I-VIIDixitB = \tempoMarkup "Allegro"
tempoH-I-VIILaudate = \tempoMarkup "[no tempo]"
  tempoH-I-VIILaudateB = \tempoMarkup "Vivace"
tempoH-I-VIILaetatus = \tempoMarkup "[no tempo]"
  tempoH-I-VIILaetatusB = \tempoMarkup "Allegro"
tempoH-I-VIINisi = \tempoMarkup "[no tempo]"
  tempoH-I-VIINisiB = \tempoMarkup "Allegro"
tempoH-I-VIILauda = \tempoMarkup "Moderato"
  tempoH-I-VIILaudaB = \tempoMarkup "Allegro"
tempoH-I-VIIMagnificat = \tempoMarkup "[no tempo]"
  tempoH-I-VIIMagnificatB = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
