\version "2.24.0"

tempoH-I-VIII-a = \tempoMarkup "[Tempo deest]"
tempoH-I-VIII-b = \tempoMarkup "[Tempo deest]"
tempoH-I-VIII-c = \tempoMarkup "[Tempo deest]"
tempoH-I-VIII-d = \tempoMarkup "[Tempo deest]"
tempoH-I-VIII-e = \tempoMarkup "[Tempo deest]"
tempoH-I-VIII-f = \tempoMarkup "[Tempo deest]"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
