\version "2.24.0"

tempoD-II-XIIa = \tempoMarkup "[Tempo deest]"
tempoD-II-XIIba = \tempoMarkup "Adagio"
  tempoD-II-XIIbb = \tempoMarkup "Allegro"
tempoD-II-XIIc = \tempoMarkup "[Tempo deest]"
tempoD-II-XIId = \tempoMarkup "[Tempo deest]"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
