\version "2.24.0"

tempoD-II-Xa = \tempoMarkup "Adagio"
tempoD-II-Xb = \tempoMarkup "Andante"
tempoD-II-Xc = \tempoMarkup "Adagio"
tempoD-II-Xd = \tempoMarkup "Presto"
tempoD-II-Xe = \tempoMarkup "[Tempo deest]"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
