\version "2.24.0"

tempoH-I-XVDixit = \tempoMarkup "Vivace"
  tempoH-I-XVDixitB = \tempoMarkup "Allegro"
tempoH-I-XVLaudate = \tempoMarkup "Allegro"
tempoH-I-XVLaetatus = \tempoMarkup "Allegro"
tempoH-I-XVNisi = \tempoMarkup "Andante"
  tempoH-I-XVNisiB = \tempoMarkup "Vivace"
tempoH-I-XVLauda = \tempoMarkup "Andante"
  tempoH-I-XVLaudaB = \tempoMarkup "Vivace"
tempoH-I-XVMagnificat = \tempoMarkup "Andante"
  tempoH-I-XVMagnificatB = \tempoMarkup "Vivace"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
