\version "2.24.0"

tempoB-LXVIIIKyrie = \tempoMarkup "[no tempo]"
  tempoB-LXVIIIChriste = \tempoMarkup "[no tempo]"
tempoB-LXVIIIGloria = \tempoMarkup "[no tempo]"
  tempoB-LXVIIIQuiTollis = \tempoMarkup "[no tempo]"
  tempoB-LXVIIIQuoniam = \tempoMarkup "[no tempo]"
tempoB-LXVIIICredo = \tempoMarkup "[no tempo]"
  tempoB-LXVIIIEtIncarnatus = \tempoMarkup "Adagio"
  tempoB-LXVIIIEtResurrexit = \tempoMarkup "[no tempo]"
  tempoB-LXVIIIEtUnam = \tempoMarkup "Ariose"
  tempoB-LXVIIIEtVitam = \tempoMarkup "Presto"
tempoB-LXVIIISanctus = \tempoMarkup "Presto"
  tempoB-LXVIIIOsanna = \tempoTitleMarkup "Osanna" "Andante"
tempoB-LXVIIIBenedictus = \tempoMarkup "[no tempo]"
tempoB-LXVIIIAgnus = \tempoMarkup "Largo"
  tempoB-LXVIIIDona = \tempoMarkup "Presto"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
