\version "2.24.0"

tempoXXXIX = \tempoMarkup "Allegro"
tempoXXXIXb = \tempoMarkup "[Tempo deest]"
tempoXXXIXc = \tempoMarkup "Recitativo · Adagio"
tempoXXXIXd = \tempoMarkup "Aria · Allegro non molto"
tempoXXXIXe = \tempoMarkup "Allegro"

\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/timp.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
