\version "2.24.0"

tempoD-II-VIa = \tempoMarkup "Allegro"
tempoD-II-VIb = \tempoMarkup "[Tempo deest]"
tempoD-II-VIc = \tempoMarkup "Recitativo · Adagio"
tempoD-II-VId = \tempoMarkup "Aria · Allegro non molto"
tempoD-II-VIe = \tempoMarkup "Allegro"

\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/timp.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
