\version "2.24.0"

tempoB-VIIKyrie = \tempoMarkup "Alla capella moderato"
  tempoB-VIIChriste = \tempoMarkup "Andante"
tempoB-VIICredo = \tempoMarkup "[no tempo]"
  tempoB-VIIEtIncarnatus = \tempoMarkup "Larghetto"
  tempoB-VIIEtResurrexit = \tempoMarkup "[no tempo]"
tempoB-VIISanctus = \tempoMarkup "[no tempo]"
tempoB-VIIBenedictus = \tempoMarkup "[no tempo]"
  tempoB-VIIOsanna = \tempoMarkup "Moderato"
tempoB-VIIAgnus = \tempoMarkup "Moderato"
  tempoB-VIIDona = \tempoMarkup "Vivace"

\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
