\version "2.24.0"

tempoH-I-Ia = \tempoMarkup "Andante"
  tempoH-I-Iab = \tempoMarkup "Vivace"
tempoH-I-Ib = \tempoMarkup "[Tempo deest]"
tempoH-I-Ic = \tempoMarkup "Andante"
tempoH-I-Id = \tempoMarkup "Vivace"
tempoH-I-Ie = \tempoMarkup "Presto"
tempoH-I-If = \tempoMarkup "Andante"
  tempoH-I-Ifb = \tempoMarkup "Vivace"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
