\version "2.24.0"

tempoB-XLIIIKyrie = \tempoMarkup "Allegro"
  tempoB-XLIIIChriste = \tempoMarkup "Andante"
  tempoB-XLIIIKyrieB = \tempoMarkup "Presto"
tempoB-XLIIIGloria = \tempoMarkup "Andante"
  tempoB-XLIIIQuiTollis = \tempoMarkup "Adagio"
  tempoB-XLIIIQuoniam = \tempoMarkup "Allegro"
  tempoB-XLIIICumSancto = \tempoMarkup "Presto"
tempoB-XLIIICredo = \tempoMarkup "Andante"
  tempoB-XLIIIEtIncarnatus = \tempoMarkup "Adagio"
  tempoB-XLIIIEtResurrexit = \tempoMarkup "Andante"
  tempoB-XLIIIEtInSpiritum = \tempoMarkup "Andante"
  tempoB-XLIIIEtVitam = \tempoMarkup "Presto"
tempoB-XLIIISanctus = \tempoMarkup "Allegro"
tempoB-XLIIIBenedictus = \tempoMarkup "Tempo ordinario"
  tempoB-XLIIIOsanna = \tempoMarkup "Presto"
tempoB-XLIIIAgnus = \tempoMarkup "Adagio"
  tempoB-XLIIIDona = \tempoMarkup "Allegro"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
