name: Release engraved scores

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  engrave_scores:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Fix git safe.directory in container
        run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig

      - name: Engrave
        uses: docker://ghcr.io/edition-esser-skala/ees-tools:v2023.10.0
        with:
          args: make -B preface works

      - name: Publish via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: final/
          remote_path: html/edition/assets/pdf/werner-collected-works/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
